import type { Profile, Audit, Task, Product, Training, Conversation, Message } from './supabase';

export const DEMO_USER_ID = 'demo-user-00000000-0000-0000-0000-000000000001';
export const DEMO_ORG_ID = 'demo-org-00000000-0000-0000-0000-000000000001';
export const DEMO_STORE_ID = 'demo-store-00000000-0000-0000-0000-000000000001';

export const DEMO_PROFILE: Profile = {
  id: DEMO_USER_ID,
  organization_id: DEMO_ORG_ID,
  store_id: DEMO_STORE_ID,
  email: 'demo@opspilot.com',
  full_name: 'Marie Dupont',
  phone: '+33 6 12 34 56 78',
  avatar_url: null,
  role: 'manager',
  department_id: null,
  level: 3,
  xp: 230,
  total_audits: 12,
  avg_score: 87,
  completed_trainings: 4,
  active_time_hours: 48,
  last_active: new Date().toISOString(),
  is_active: true,
  created_at: '2024-06-01T08:00:00Z',
  updated_at: new Date().toISOString(),
};

const today = new Date();
const daysAgo = (n: number) => new Date(today.getTime() - n * 86400000).toISOString();

export const DEMO_AUDITS: Audit[] = [
  {
    id: 'demo-audit-001',
    organization_id: DEMO_ORG_ID,
    store_id: DEMO_STORE_ID,
    auditor_id: DEMO_USER_ID,
    title: 'Audit rayon frais',
    description: 'Controle qualite du rayon frais',
    location: 'Magasin Bordeaux Centre',
    status: 'completed',
    score: 92,
    max_score: 100,
    issues_count: 1,
    photos: [],
    notes: 'Bon etat general',
    started_at: daysAgo(2),
    completed_at: daysAgo(2),
    due_date: daysAgo(1),
    created_at: daysAgo(3),
    updated_at: daysAgo(2),
  },
  {
    id: 'demo-audit-002',
    organization_id: DEMO_ORG_ID,
    store_id: DEMO_STORE_ID,
    auditor_id: DEMO_USER_ID,
    title: 'Audit securite magasin',
    description: 'Verification des normes de securite',
    location: 'Magasin Bordeaux Centre',
    status: 'in_progress',
    score: null,
    max_score: 100,
    issues_count: 3,
    photos: [],
    notes: null,
    started_at: daysAgo(1),
    completed_at: null,
    due_date: daysAgo(-2),
    created_at: daysAgo(1),
    updated_at: daysAgo(0),
  },
  {
    id: 'demo-audit-003',
    organization_id: DEMO_ORG_ID,
    store_id: DEMO_STORE_ID,
    auditor_id: DEMO_USER_ID,
    title: 'Audit hygiene cuisine',
    description: 'Controle HACCP',
    location: 'Magasin Lyon Part-Dieu',
    status: 'pending',
    score: null,
    max_score: 100,
    issues_count: 0,
    photos: [],
    notes: null,
    started_at: null,
    completed_at: null,
    due_date: daysAgo(-5),
    created_at: daysAgo(0),
    updated_at: daysAgo(0),
  },
  {
    id: 'demo-audit-004',
    organization_id: DEMO_ORG_ID,
    store_id: DEMO_STORE_ID,
    auditor_id: DEMO_USER_ID,
    title: 'Audit merchandising',
    description: 'Verification de la mise en rayon',
    location: 'Magasin Paris Republique',
    status: 'completed',
    score: 78,
    max_score: 100,
    issues_count: 4,
    photos: [],
    notes: 'Ameliorations necessaires sur le facing',
    started_at: daysAgo(5),
    completed_at: daysAgo(4),
    due_date: daysAgo(3),
    created_at: daysAgo(6),
    updated_at: daysAgo(4),
  },
];

export const DEMO_TASKS: Task[] = [
  {
    id: 'demo-task-001',
    organization_id: DEMO_ORG_ID,
    store_id: DEMO_STORE_ID,
    assigned_to: DEMO_USER_ID,
    created_by: DEMO_USER_ID,
    title: 'Reapprovisionner rayon frais',
    description: 'Verifier les DLC et remplir les rayons avant ouverture',
    location: 'Magasin Bordeaux Centre',
    priority: 'high',
    status: 'pending',
    estimated_time_minutes: 45,
    due_date: daysAgo(-1),
    created_at: daysAgo(0),
    updated_at: daysAgo(0),
    completed_at: null,
  },
  {
    id: 'demo-task-002',
    organization_id: DEMO_ORG_ID,
    store_id: DEMO_STORE_ID,
    assigned_to: DEMO_USER_ID,
    created_by: DEMO_USER_ID,
    title: 'Mettre a jour affichage prix',
    description: 'Changer les etiquettes suite a la promo hebdomadaire',
    location: 'Magasin Bordeaux Centre',
    priority: 'medium',
    status: 'in_progress',
    estimated_time_minutes: 30,
    due_date: daysAgo(-1),
    created_at: daysAgo(1),
    updated_at: daysAgo(0),
    completed_at: null,
  },
  {
    id: 'demo-task-003',
    organization_id: DEMO_ORG_ID,
    store_id: DEMO_STORE_ID,
    assigned_to: DEMO_USER_ID,
    created_by: DEMO_USER_ID,
    title: 'Inventaire rayon boulangerie',
    description: 'Comptage physique des stocks',
    location: 'Magasin Lyon Part-Dieu',
    priority: 'low',
    status: 'completed',
    estimated_time_minutes: 60,
    due_date: daysAgo(1),
    created_at: daysAgo(3),
    updated_at: daysAgo(1),
    completed_at: daysAgo(1),
  },
  {
    id: 'demo-task-004',
    organization_id: DEMO_ORG_ID,
    store_id: DEMO_STORE_ID,
    assigned_to: DEMO_USER_ID,
    created_by: DEMO_USER_ID,
    title: 'Nettoyage zone stockage',
    description: 'Nettoyage et reorganisation de la reserve',
    location: 'Magasin Bordeaux Centre',
    priority: 'medium',
    status: 'pending',
    estimated_time_minutes: 90,
    due_date: daysAgo(-3),
    created_at: daysAgo(0),
    updated_at: daysAgo(0),
    completed_at: null,
  },
];

export const DEMO_PRODUCTS: Product[] = [
  {
    id: 'demo-prod-001',
    organization_id: DEMO_ORG_ID,
    name: 'Lait demi-ecreme 1L',
    barcode: '3045320073034',
    category: 'Produits laitiers',
    price: 1.15,
    stock_quantity: 48,
    min_stock: 20,
    dlc: daysAgo(-5),
    image_url: null,
    added_by: DEMO_USER_ID,
    created_at: daysAgo(30),
    updated_at: daysAgo(0),
  },
  {
    id: 'demo-prod-002',
    organization_id: DEMO_ORG_ID,
    name: 'Pain de mie complet',
    barcode: '3564700456789',
    category: 'Boulangerie',
    price: 2.30,
    stock_quantity: 5,
    min_stock: 10,
    dlc: daysAgo(-2),
    image_url: null,
    added_by: DEMO_USER_ID,
    created_at: daysAgo(30),
    updated_at: daysAgo(0),
  },
  {
    id: 'demo-prod-003',
    organization_id: DEMO_ORG_ID,
    name: 'Eau minerale 1.5L',
    barcode: '3274080005003',
    category: 'Boissons',
    price: 0.65,
    stock_quantity: 120,
    min_stock: 30,
    dlc: daysAgo(-90),
    image_url: null,
    added_by: DEMO_USER_ID,
    created_at: daysAgo(30),
    updated_at: daysAgo(0),
  },
  {
    id: 'demo-prod-004',
    organization_id: DEMO_ORG_ID,
    name: 'Beurre doux 250g',
    barcode: '3229820787152',
    category: 'Produits laitiers',
    price: 2.85,
    stock_quantity: 0,
    min_stock: 10,
    dlc: daysAgo(-3),
    image_url: null,
    added_by: DEMO_USER_ID,
    created_at: daysAgo(30),
    updated_at: daysAgo(0),
  },
  {
    id: 'demo-prod-005',
    organization_id: DEMO_ORG_ID,
    name: 'Pates spaghetti 500g',
    barcode: '3560070462235',
    category: 'Epicerie',
    price: 1.45,
    stock_quantity: 72,
    min_stock: 15,
    dlc: daysAgo(-180),
    image_url: null,
    added_by: DEMO_USER_ID,
    created_at: daysAgo(30),
    updated_at: daysAgo(0),
  },
  {
    id: 'demo-prod-006',
    organization_id: DEMO_ORG_ID,
    name: 'Yaourt nature x4',
    barcode: '3033490004002',
    category: 'Produits laitiers',
    price: 1.90,
    stock_quantity: 3,
    min_stock: 15,
    dlc: daysAgo(-4),
    image_url: null,
    added_by: DEMO_USER_ID,
    created_at: daysAgo(30),
    updated_at: daysAgo(0),
  },
];

export const DEMO_TRAININGS: Training[] = [
  {
    id: 'demo-training-001',
    organization_id: DEMO_ORG_ID,
    title: 'Accueil client en magasin',
    content: 'Techniques d\'accueil et de service client pour les equipes terrain.',
    category: 'Service client',
    difficulty: 'beginner',
    duration_minutes: 25,
    xp_reward: 50,
    is_active: true,
    ai_generated: false,
    created_at: daysAgo(30),
    updated_at: daysAgo(30),
  },
  {
    id: 'demo-training-002',
    organization_id: DEMO_ORG_ID,
    title: 'Hygiene et securite alimentaire',
    content: 'Normes HACCP et bonnes pratiques de manipulation des denrees.',
    category: 'Securite',
    difficulty: 'intermediate',
    duration_minutes: 40,
    xp_reward: 80,
    is_active: true,
    ai_generated: false,
    created_at: daysAgo(25),
    updated_at: daysAgo(25),
  },
  {
    id: 'demo-training-003',
    organization_id: DEMO_ORG_ID,
    title: 'Gestion des stocks et commandes',
    content: 'Methodes de gestion des stocks, seuils de reapprovisionnement et previsions.',
    category: 'Logistique',
    difficulty: 'advanced',
    duration_minutes: 50,
    xp_reward: 100,
    is_active: true,
    ai_generated: false,
    created_at: daysAgo(20),
    updated_at: daysAgo(20),
  },
  {
    id: 'demo-training-004',
    organization_id: DEMO_ORG_ID,
    title: 'Techniques de merchandising',
    content: 'Optimisation de la presentation produits et du facing.',
    category: 'Vente',
    difficulty: 'beginner',
    duration_minutes: 30,
    xp_reward: 60,
    is_active: true,
    ai_generated: false,
    created_at: daysAgo(15),
    updated_at: daysAgo(15),
  },
];

export const DEMO_CONVERSATIONS: Conversation[] = [
  {
    id: 'demo-conv-team',
    organization_id: DEMO_ORG_ID,
    name: 'Equipe Magasin',
    description: 'Chat general de l\'equipe',
    type: 'group',
    participants: [DEMO_USER_ID],
    last_message_at: daysAgo(0),
    created_by: DEMO_USER_ID,
    created_at: daysAgo(30),
  },
  {
    id: 'demo-conv-ai',
    organization_id: DEMO_ORG_ID,
    name: 'Assistant IA OpsPilot',
    description: 'Support et aide',
    type: 'support',
    participants: [DEMO_USER_ID],
    last_message_at: daysAgo(0),
    created_by: DEMO_USER_ID,
    created_at: daysAgo(30),
  },
];

export const DEMO_MESSAGES: Message[] = [
  {
    id: 'demo-msg-001',
    conversation_id: 'demo-conv-team',
    sender_id: 'other-user',
    content: 'Bonjour a tous ! Bonne journee.',
    message_type: 'text',
    attachments: [],
    read_by: [DEMO_USER_ID],
    created_at: daysAgo(0),
  },
  {
    id: 'demo-msg-002',
    conversation_id: 'demo-conv-ai',
    sender_id: 'ai-assistant',
    content: 'Bienvenue sur OpsPilot ! Je suis votre assistant IA. Comment puis-je vous aider ?',
    message_type: 'text',
    attachments: [],
    read_by: [DEMO_USER_ID],
    created_at: daysAgo(0),
  },
];
