import type { Audit, CorrectiveAction, Product, Task } from './supabase';

/**
 * Données de démonstration en mémoire.
 * Utilisées quand isDemoMode && !session (Supabase injoignable) :
 * le dashboard et les listes affichent des données réalistes, jamais vides.
 * Les dates sont relatives à « maintenant » pour que les KPIs
 * (audits en retard, DLC critiques…) soient toujours non-nuls.
 */

export const DEMO_ORG_ID = 'demo-org-00000000-0000-0000-0000-000000000001';
export const DEMO_USER_ID = 'demo-user-00000000-0000-0000-0000-000000000001';

const days = (n: number) => new Date(Date.now() + n * 86_400_000).toISOString();

const base = {
  organization_id: DEMO_ORG_ID,
  store_id: null,
};

export function getDemoAudits(): Audit[] {
  return [
    {
      ...base,
      id: 'demo-audit-1',
      auditor_id: DEMO_USER_ID,
      title: 'Contrôle hygiène rayon frais',
      description: 'Audit quotidien température + propreté',
      location: 'Rayon frais',
      status: 'completed',
      score: 92,
      max_score: 100,
      issues_count: 1,
      photos: [],
      started_at: days(-1),
      completed_at: days(-1),
      due_date: days(-1),
      created_at: days(-1),
      updated_at: days(-1),
    },
    {
      ...base,
      id: 'demo-audit-2',
      auditor_id: DEMO_USER_ID,
      title: 'Vérification chambre froide',
      description: 'Relevé températures et joints de porte',
      location: 'Réserve',
      status: 'completed',
      score: 88,
      max_score: 100,
      issues_count: 2,
      photos: [],
      started_at: days(-3),
      completed_at: days(-3),
      due_date: days(-3),
      created_at: days(-3),
      updated_at: days(-3),
    },
    {
      ...base,
      id: 'demo-audit-3',
      auditor_id: DEMO_USER_ID,
      title: 'Audit DLC boulangerie',
      description: 'Contrôle des dates et rotation des stocks',
      location: 'Boulangerie',
      status: 'completed',
      score: 76,
      max_score: 100,
      issues_count: 4,
      photos: [],
      started_at: days(-6),
      completed_at: days(-6),
      due_date: days(-6),
      created_at: days(-6),
      updated_at: days(-6),
    },
    {
      ...base,
      id: 'demo-audit-4',
      auditor_id: DEMO_USER_ID,
      title: 'Contrôle affichage prix',
      description: 'Cohérence étiquettes / caisse',
      location: 'Surface de vente',
      status: 'in_progress',
      score: null,
      max_score: 100,
      issues_count: 0,
      photos: [],
      started_at: days(-1),
      completed_at: null,
      due_date: days(-1),
      created_at: days(-2),
      updated_at: days(-1),
    },
    {
      ...base,
      id: 'demo-audit-5',
      auditor_id: DEMO_USER_ID,
      title: 'Audit sécurité incendie',
      description: 'Extincteurs, issues de secours, BAES',
      location: 'Tout le magasin',
      status: 'pending',
      score: null,
      max_score: 100,
      issues_count: 0,
      photos: [],
      started_at: null,
      completed_at: null,
      due_date: days(-2),
      created_at: days(-5),
      updated_at: days(-5),
    },
    {
      ...base,
      id: 'demo-audit-6',
      auditor_id: DEMO_USER_ID,
      title: 'Tournée propreté parking',
      description: 'Chariots, poubelles, signalétique',
      location: 'Extérieur',
      status: 'pending',
      score: null,
      max_score: 100,
      issues_count: 0,
      photos: [],
      started_at: null,
      completed_at: null,
      due_date: days(2),
      created_at: days(0),
      updated_at: days(0),
    },
  ];
}

export function getDemoProducts(): Product[] {
  const p = (
    id: string,
    name: string,
    category: string,
    dlc: string | null,
    stock: number,
    price: number,
    barcode: string,
  ): Product => ({
    ...base,
    id,
    name,
    barcode,
    category,
    price,
    stock_quantity: stock,
    min_stock: 5,
    dlc,
    image_url: null,
    added_by: DEMO_USER_ID,
    created_at: days(-30),
    updated_at: days(-1),
  });

  return [
    p(
      'demo-prod-1',
      'Yaourt nature x8',
      'Crèmerie',
      days(1),
      24,
      2.49,
      '3000000000001',
    ),
    p(
      'demo-prod-2',
      'Jambon blanc 4 tranches',
      'Charcuterie',
      days(-1),
      8,
      3.2,
      '3000000000002',
    ),
    p(
      'demo-prod-3',
      'Saumon fumé 120g',
      'Marée',
      days(2),
      6,
      6.9,
      '3000000000003',
    ),
    p(
      'demo-prod-4',
      'Salade composée poulet',
      'Snacking',
      days(0),
      12,
      4.5,
      '3000000000004',
    ),
    p(
      'demo-prod-5',
      'Lait demi-écrémé 1L',
      'Crèmerie',
      days(12),
      60,
      1.15,
      '3000000000005',
    ),
    p(
      'demo-prod-6',
      'Beurre doux 250g',
      'Crèmerie',
      days(20),
      30,
      2.8,
      '3000000000006',
    ),
    p(
      'demo-prod-7',
      'Steak haché 2x125g',
      'Boucherie',
      days(3),
      14,
      4.9,
      '3000000000007',
    ),
    p(
      'demo-prod-8',
      'Pain de mie complet',
      'Boulangerie',
      days(6),
      18,
      1.9,
      '3000000000008',
    ),
    p(
      'demo-prod-9',
      'Jus d’orange frais 1L',
      'Frais',
      days(5),
      10,
      2.95,
      '3000000000009',
    ),
    p(
      'demo-prod-10',
      'Crème fraîche 30cl',
      'Crèmerie',
      days(9),
      22,
      1.75,
      '3000000000010',
    ),
    p(
      'demo-prod-11',
      'Pizza margherita',
      'Surgelés',
      days(120),
      16,
      3.5,
      '3000000000011',
    ),
    p(
      'demo-prod-12',
      'Eau minérale 6x1,5L',
      'Boissons',
      null,
      45,
      3.1,
      '3000000000012',
    ),
  ];
}

export function getDemoActions(): CorrectiveAction[] {
  return [
    {
      ...base,
      id: 'demo-action-1',
      audit_id: 'demo-audit-3',
      audit_response_id: null,
      title: 'Retirer les produits DLC dépassée (boulangerie)',
      description: 'Retrait immédiat + traçabilité dans le registre',
      assignee_id: DEMO_USER_ID,
      priority: 'critical',
      status: 'open',
      due_date: days(0),
      resolved_at: null,
      created_by: DEMO_USER_ID,
      created_at: days(-6),
      updated_at: days(-6),
    },
    {
      ...base,
      id: 'demo-action-2',
      audit_id: 'demo-audit-2',
      audit_response_id: null,
      title: 'Remplacer le joint de la chambre froide n°2',
      description: 'Joint usé constaté lors de l’audit',
      assignee_id: DEMO_USER_ID,
      priority: 'high',
      status: 'in_progress',
      due_date: days(3),
      resolved_at: null,
      created_by: DEMO_USER_ID,
      created_at: days(-3),
      updated_at: days(-1),
    },
    {
      ...base,
      id: 'demo-action-3',
      audit_id: 'demo-audit-1',
      audit_response_id: null,
      title: 'Nettoyer la vitrine du rayon frais',
      description: 'Traces constatées côté client',
      assignee_id: DEMO_USER_ID,
      priority: 'medium',
      status: 'open',
      due_date: days(2),
      resolved_at: null,
      created_by: DEMO_USER_ID,
      created_at: days(-1),
      updated_at: days(-1),
    },
    {
      ...base,
      id: 'demo-action-4',
      audit_id: null,
      audit_response_id: null,
      title: 'Mettre à jour l’affichage allergènes',
      description: 'Nouvelle recette snacking',
      assignee_id: DEMO_USER_ID,
      priority: 'low',
      status: 'done',
      due_date: days(-2),
      resolved_at: days(-2),
      created_by: DEMO_USER_ID,
      created_at: days(-8),
      updated_at: days(-2),
    },
    {
      ...base,
      id: 'demo-action-5',
      audit_id: null,
      audit_response_id: null,
      title: 'Former l’équipe au nouveau plan de nettoyage',
      description: 'Session 30 min, support fourni',
      assignee_id: DEMO_USER_ID,
      priority: 'medium',
      status: 'done',
      due_date: days(-5),
      resolved_at: days(-5),
      created_by: DEMO_USER_ID,
      created_at: days(-10),
      updated_at: days(-5),
    },
  ];
}

export function getDemoTasks(): Task[] {
  return [
    {
      ...base,
      id: 'demo-task-1',
      assigned_to: DEMO_USER_ID,
      created_by: DEMO_USER_ID,
      title: 'Réassort rayon crèmerie',
      description: 'Compléter les yaourts et le lait',
      location: 'Crèmerie',
      priority: 'high',
      status: 'pending',
      estimated_time_minutes: 30,
      due_date: days(0),
      created_at: days(-1),
      updated_at: days(-1),
      completed_at: null,
    },
    {
      ...base,
      id: 'demo-task-2',
      assigned_to: DEMO_USER_ID,
      created_by: DEMO_USER_ID,
      title: 'Relevé des températures matin',
      description: 'Chambres froides + vitrines',
      location: 'Réserve',
      priority: 'urgent',
      status: 'in_progress',
      estimated_time_minutes: 15,
      due_date: days(0),
      created_at: days(0),
      updated_at: days(0),
      completed_at: null,
    },
    {
      ...base,
      id: 'demo-task-3',
      assigned_to: DEMO_USER_ID,
      created_by: DEMO_USER_ID,
      title: 'Préparer la commande fournisseur',
      description: 'Volumes semaine prochaine',
      location: 'Bureau',
      priority: 'medium',
      status: 'pending',
      estimated_time_minutes: 45,
      due_date: days(1),
      created_at: days(-1),
      updated_at: days(-1),
      completed_at: null,
    },
    {
      ...base,
      id: 'demo-task-4',
      assigned_to: DEMO_USER_ID,
      created_by: DEMO_USER_ID,
      title: 'Vérifier la propreté de l’accueil',
      description: 'Tournée de contrôle',
      location: 'Accueil',
      priority: 'low',
      status: 'completed',
      estimated_time_minutes: 10,
      due_date: days(-1),
      created_at: days(-2),
      updated_at: days(-1),
      completed_at: days(-1),
    },
  ];
}

/** Génère un identifiant local unique pour les créations en mode démo. */
export function demoId(prefix: string): string {
  return `${prefix}-${Date.now()}-${Math.floor(Math.random() * 10_000)}`;
}
